### PR TITLE
remove github pages files

### PR DESCRIPTION
**Pull request by tsloughter**
Now that you are using readme.io I figured the files could be cleaned up.

Curious if `RIAK.md` and `EQC_CI_LICENCE.txt` are actually needed though?

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
No, you can remove them as well.

**Comment by cmeiklejohn** [comment]
Please leave the images, but move them somewhere else.  This is where people go to get the assets.

**Comment by tsloughter** [comment]
OK, I added back the images. Not sure of a better place to put them then where they are though.

**Comment by cmeiklejohn** [comment]
Hrm, isn't that dtl file required for the internal webmachine interface?

**Comment by cmeiklejohn** [comment]
It looks like things that are used for the homepage and things that are required for the webmachine interface are conflated in this PR, please make sure this is one removing the stuff related to the deprecated homepage.

**Comment by tsloughter** [comment]
Oh, hm, I thought anything related to the webmachine interface was under `priv/`.

I can't find any reference to the index dtl file or use of a dtl template renderer.

**Pull request merged**
