### PR TITLE
move partisan to applications from included_apps

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
I think you need to bump partisan in the rebar.config, right?

**Comment by tsloughter** [comment]
Argh, this is what I get for merging without enough morning coffee.

**Comment by cmeiklejohn** [comment]
Once this passes, I'll verify the runs still complete on Amazon before we merge it.

**Comment by cmeiklejohn** [comment]
Change the target branch to `unstable` when you have a moment.

**Comment by cmeiklejohn** [comment]
See #210.

**Pull request closed without merging**
