### PR TITLE
Added logo.

### PR DESCRIPTION
**Pull request by oubiwann**
Created a lattice and Escher-inspired logo.

Added several sizes; I also have a GIMP .xcf file (not added to git), should you 1) like this logo, and 2) want to make any changes to it.

### CODE REVIEW

**Comment by oubiwann** [comment]
Also, I wanted to make sure that proper credit was given: this logo was inspired by this design, by Regolino Bizzi:
 * https://s-media-cache-ak0.pinimg.com/originals/98/37/65/98376571f8cbc22fb3fd838404a5e9c0.jpg

Here is an interview with the artist (who lives in Stockholm, btw):
 * http://creativeroom4talk.com/interview-regolino-bizzi/

**Comment by cmeiklejohn** [comment]
Thanks!

**Comment by cmeiklejohn** [comment]
I'm thinking that we modify the page with the attribution to you and the original author?  Do you mind opening a PR for that?

**Comment by oubiwann** [comment]
Sure thing.

**Pull request merged**
