### PR TITLE
Push logs to S3

### PR DESCRIPTION
**Pull request by vitorenesduarte**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
Did you test this?

**Comment by vitorenesduarte** [comment]
No.

**Comment by vitorenesduarte** [comment]
It assumes a bucket named __logs__.
Also, just noticed there might be a problem in the put_object part.
It's a list. 
Let me make that a string.

**Comment by cmeiklejohn** [comment]
Can you also make sure to call create_bucket like we do in the sprinter code when it starts?

**Comment by cmeiklejohn** [comment]
Yes, I believe put_object needs a binary.

**Comment by cmeiklejohn** [comment]
Yes, it does require a binary.

**Pull request merged**
