### PR TITLE
version bump and upgrade partisan

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
This is failing.

**Comment by tsloughter** [comment]
Ah yea, partisan api changed. I can look at it later, but maybe @lrascao can see quicker exactly what the modifications needed in lasp are?

**Comment by lrascao** [comment]
the biggest breaking change and the one that seems to be causing the failed tests is the new join api, an example can be found here: https://github.com/lrascao/plumtree/commit/a23fca6563d2a8440d8fc4587d4bc2bedb770c3d

**Comment by cmeiklejohn** [comment]
@tsloughter please push a new release to hex when you have time, thanks!

**Pull request merged**
