### PR TITLE
update gen_flow to 0.0.4

### PR DESCRIPTION
**Pull request by evanmcc**
in order to clean up 'EXIT' messages.

### CODE REVIEW

**Comment by evanmcc** [comment]
closes #253

**Comment by cmeiklejohn** [comment]
Looks like the tests are failing.

**Comment by evanmcc** [comment]
the failure is in xref, and seems to be OTP release specific, rather than anything to do with the changed code.

**Comment by cmeiklejohn** [comment]
I'm removing 20 from the OTP build, because there's a number of issues surrounding full OTP 20 support, it seems.

**Pull request merged**
